'use client';

import { useEffect, useRef, useState, useCallback } from 'react';
import { useRouter } from 'next/navigation';
import Image from 'next/image';
import * as THREE from 'three';
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader.js';
import { ARButton } from 'three/examples/jsm/webxr/ARButton.js';
import { createThreeScene } from '@/lib/threeScene';
import { getDistanceMeters, getBearing } from '@/lib/geo';
import { ControlPanel } from '@/components/ControlPanel';
import { GuideContent } from '@/components/GuideContent';
import type { MeshItem, ModelSize } from '@/types/mesh';

function setMeshMaterialOpacity(mesh: THREE.Mesh, opacity: number): void {
  const materials = Array.isArray(mesh.material) ? mesh.material : [mesh.material];
  materials.forEach((m) => {
    m.transparent = true;
    m.opacity = opacity;
  });
}

/** 모델 바운딩에 맞춰 카메라 거리·타겟 조정 (규모 있는 모델 잘림 방지) */
function frameCameraToModel(
  ctx: { camera: THREE.PerspectiveCamera; controls: { target: THREE.Vector3; update: () => void } },
  model: THREE.Object3D,
  padding = 1.5
): void {
  const box = new THREE.Box3().setFromObject(model);
  const sphere = new THREE.Sphere();
  box.getBoundingSphere(sphere);
  const radius = sphere.radius;
  const fovRad = (ctx.camera.fov * Math.PI) / 180;
  const distance = Math.max(0.5, (radius / Math.tan(fovRad / 2)) * padding);
  ctx.camera.position.set(sphere.center.x, sphere.center.y, sphere.center.z + distance);
  ctx.controls.target.copy(sphere.center);
  ctx.controls.update();
}

/** SketchUp/glTF 자동 생성 이름 패턴 (무시하고 부모 이름 우선 사용) */
const AUTO_GENERATED_NAME_PATTERN =
  /^(Geom3D_\d+|Mesh_\d+|mesh_\d+|Object_\d+|Primitive\d+|Shape_\d+|Node_\d+|\d+)$/i;

/** GLB 노드/메시의 표시 이름 반환 (스케치업 그룹명 우선, 메시 → 부모 순 탐색) */
function getObjectDisplayName(obj: THREE.Object3D): string {
  const isAutoGenerated = (name: string) =>
    AUTO_GENERATED_NAME_PATTERN.test(name.trim()) || /^default(_\d+)?$/i.test(name.trim());

  // 현재 이름이 자동 생성 패턴이면 부모에서 사용자 지정 이름 먼저 탐색
  const currentName = obj.name?.trim() ?? '';
  const skipCurrent = !currentName || isAutoGenerated(currentName);

  if (!skipCurrent) return currentName;

  let parent = obj.parent;
  while (parent) {
    const parentName = parent.name?.trim() ?? '';
    if (parentName && !isAutoGenerated(parentName) && !/^(Scene|Root|Group)$/i.test(parentName)) {
      return parentName;
    }
    parent = parent.parent;
  }

  return currentName || 'Unnamed';
}

function isIOS(): boolean {
  if (typeof navigator === 'undefined') return false;
  return /iPhone|iPad|iPod/i.test(navigator.userAgent);
}

function isMobile(): boolean {
  if (typeof navigator === 'undefined') return false;
  return /Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent);
}

export interface ARViewerProps {
  className?: string;
  meshItems: MeshItem[];
  setMeshItems: React.Dispatch<React.SetStateAction<MeshItem[]>>;
  setModelSize: React.Dispatch<React.SetStateAction<ModelSize | null>>;
  /** 지정번호로 불러온 모델 URL (blob 또는 API URL) */
  initialModelUrl?: string | null;
  /** 모델의 실제 위치 (위경도, 고도). Location ON 시 사용 */
  modelGeoLocation?: { lat: number; lon: number; alt: number } | null;
  /** 현재 AR 페이지의 지정번호 (iOS 네이티브 앱 열기용) */
  arCode?: string;
}

export function ARViewer({ className = '', meshItems, setMeshItems, setModelSize, initialModelUrl, modelGeoLocation, arCode }: ARViewerProps) {
  const router = useRouter();
  const containerRef = useRef<HTMLDivElement>(null);
  const arButtonContainerRef = useRef<HTMLDivElement>(null);
  const contextRef = useRef<ReturnType<typeof createThreeScene> | null>(null);
  const loadedSceneRef = useRef<THREE.Group | null>(null);
  const meshByIdRef = useRef<Map<string, THREE.Mesh>>(new Map());
  const arPlaceableRef = useRef<THREE.Group | null>(null);
  const arPlaceableGeoRef = useRef<THREE.Group | null>(null);
  const reticleRef = useRef<THREE.Mesh | null>(null);
  const tapPlacedRef = useRef<THREE.Group[]>([]);
  const geoPlacedRef = useRef<THREE.Group | null>(null);
  const geoMarkerRef = useRef<THREE.Mesh | null>(null);
  const arrowIndicatorRef = useRef<HTMLDivElement | null>(null);
  const arrowDistanceRef = useRef<HTMLSpanElement | null>(null);
  const locationModeActiveRef = useRef(false);
  const modelGeoLocationRef = useRef(modelGeoLocation);
  const GEO_PLACEMENT_MAX_RETRIES = 300;
  const geoPlacementPendingRef = useRef<{
    horizontalDist: number;
    deltaAlt: number;
    bearing: number;
    deviceHeading: number | null;
    retryCount: number;
  } | null>(null);
  modelGeoLocationRef.current = modelGeoLocation;
  const arCodeRef = useRef(arCode);
  arCodeRef.current = arCode;
  const hitTestSourceRef = useRef<XRHitTestSource | null>(null);
  const hitTestSourceRequestedRef = useRef(false);
  const arButtonRef = useRef<HTMLButtonElement | null>(null);
  const arOverlayRef = useRef<HTMLDivElement | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [menuExpanded, setMenuExpanded] = useState(false);
  const [guideModalOpen, setGuideModalOpen] = useState(false);
  const [locationModeActive, setLocationModeActive] = useState(false);
  const [locationOffsetPanelExpanded, setLocationOffsetPanelExpanded] = useState(true);
  const [locationRefreshLoading, setLocationRefreshLoading] = useState(false);
  const [locationOnError, setLocationOnError] = useState<string | null>(null);
  const [locationOnInfo, setLocationOnInfo] = useState<string | null>(null);
  const [userGeoLocation, setUserGeoLocation] = useState<{ lat: number; lon: number; alt: number } | null>(null);
  const [targetOffset, setTargetOffset] = useState({ lat: 0, lon: 0, alt: 0 });
  const targetOffsetRef = useRef({ lat: 0, lon: 0, alt: 0 });
  const lastPlacementDeviceHeadingRef = useRef<number | null>(null);
  targetOffsetRef.current = targetOffset;
  const setLocationOnErrorRef = useRef(setLocationOnError);
  const setLocationModeActiveRef = useRef(setLocationModeActive);
  const geolocationWatchIdRef = useRef<number | null>(null);
  const placementSetupDoneRef = useRef(false);
  const bestPositionRef = useRef<{
    lat: number;
    lon: number;
    alt: number;
    accuracy: number;
  } | null>(null);
  const smoothedPositionRef = useRef<{ lat: number; lon: number; alt: number } | null>(null);
  const positionWindowRef = useRef<{ lat: number; lon: number; alt: number }[]>([]);
  const lastUserGeoUpdateRef = useRef<number>(0);
  const placementTimeoutRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  setLocationOnErrorRef.current = setLocationOnError;
  setLocationModeActiveRef.current = setLocationModeActive;

  useEffect(() => {
    if (!containerRef.current || !arButtonContainerRef.current) return;

    const onXRFrame = (frame: XRFrame) => {
      const ctx = contextRef.current;
      const reticle = reticleRef.current;
      if (!ctx || !reticle) return;

      const session = ctx.renderer.xr.getSession();
      if (!session) return;

      if (!hitTestSourceRequestedRef.current) {
        hitTestSourceRequestedRef.current = true;
        session.requestReferenceSpace('viewer').then((viewerSpace: XRReferenceSpace) => {
          const sessionWithHitTest = session as XRSession & {
            requestHitTestSource?(options: { space: XRReferenceSpace }): Promise<XRHitTestSource>;
          };
          const promise = sessionWithHitTest.requestHitTestSource?.({ space: viewerSpace });
          if (promise) {
            promise.then((source) => {
              hitTestSourceRef.current = source;
            });
          }
        });
        session.addEventListener('end', () => {
          hitTestSourceRequestedRef.current = false;
          hitTestSourceRef.current = null;
        });
      }

      const refSpace = ctx.renderer.xr.getReferenceSpace();
      if (!refSpace) return;

      const hitTestSource = hitTestSourceRef.current;
      if (locationModeActiveRef.current) {
        reticle.visible = false;
        const geoPlaced = geoPlacedRef.current;
        const arrowEl = arrowIndicatorRef.current;
        const viewerPose = frame.getViewerPose(refSpace);
        if (geoPlaced && arrowEl && ctx.camera && viewerPose) {
          const pos = viewerPose.transform.position;
          const ori = viewerPose.transform.orientation;
          const projCam = ctx.camera.clone();
          projCam.position.set(pos.x, pos.y, pos.z);
          projCam.quaternion.set(ori.x, ori.y, ori.z, ori.w);
          const views = viewerPose.views;
          if (views?.length) {
            projCam.projectionMatrix.fromArray(views[0].projectionMatrix);
            projCam.projectionMatrixInverse.copy(projCam.projectionMatrix).invert();
          }
          projCam.updateMatrixWorld(true);

          const modelPos = new THREE.Vector3();
          geoPlaced.getWorldPosition(modelPos);
          const camPos = projCam.position;
          const dirToModel = new THREE.Vector3().subVectors(modelPos, camPos);
          const dirLen = dirToModel.length();
          const tempVec = new THREE.Vector3().copy(modelPos);

          let dx = 0;
          let dy = 0;
          const width = ctx.renderer.domElement.clientWidth;
          const height = ctx.renderer.domElement.clientHeight;
          const margin = 48;
          const cx = width / 2;
          const cy = height / 2;
          const maxDist = Math.min(cx, cy) - margin;

          let shouldHideArrow = dirLen <= 20;

          if (!shouldHideArrow && dirLen >= 1e-6) {
            tempVec.project(projCam);
            const behind = tempVec.z > 1 || tempVec.z < -1;
            if (behind) {
              const dirView = dirToModel.clone().transformDirection(projCam.matrixWorldInverse);
              const vx = dirView.x;
              const vy = -dirView.y;
              const len = Math.sqrt(vx * vx + vy * vy) || 1;
              dx = (vx / len) * maxDist;
              dy = (vy / len) * maxDist;
            } else {
              const x = ((tempVec.x + 1) / 2) * width;
              const y = ((1 - tempVec.y) / 2) * height;
              const onScreen = x >= 0 && x <= width && y >= 0 && y <= height;
              if (onScreen) {
                shouldHideArrow = true;
              } else {
                dx = x - cx;
                dy = y - cy;
                const dist = Math.sqrt(dx * dx + dy * dy) || 1;
                const scale = Math.min(1, maxDist / dist);
                dx *= scale;
                dy *= scale;
              }
            }
          }

          if (width > 0 && height > 0 && !shouldHideArrow) {
            const clipX = cx + dx;
            const clipY = cy + dy;
            const angle = Math.atan2(dx, -dy) * (180 / Math.PI);
            arrowEl.style.left = `${clipX}px`;
            arrowEl.style.top = `${clipY}px`;
            arrowEl.style.transform = `translate(-50%, -50%) rotate(${angle}deg)`;
            arrowEl.style.display = 'flex';
            const distM = Math.round(dirLen);
            const distText = arrowDistanceRef.current;
            if (distText) {
              distText.textContent = `${distM}M`;
            }
          } else if (width > 0 && height > 0) {
            arrowEl.style.display = 'none';
          }
        }
      } else if (hitTestSource) {
        const hitTestResults = frame.getHitTestResults(hitTestSource);
          if (hitTestResults.length > 0) {
            const hit = hitTestResults[0];
            const pose = hit.getPose(refSpace);
            if (pose) {
              reticle.visible = true;
              reticle.matrix.fromArray(pose.transform.matrix);
            }
          } else {
            reticle.visible = false;
          }
      }

      const pending = geoPlacementPendingRef.current;
      if (pending) {
        const arModel = arPlaceableGeoRef.current ?? arPlaceableRef.current;
        const viewerPose = frame.getViewerPose(refSpace);
        if (arModel && viewerPose) {
          const pos = viewerPose.transform.position;
          const ori = viewerPose.transform.orientation;
          const viewerPos = new THREE.Vector3(pos.x, pos.y, pos.z);
          const viewerQuat = new THREE.Quaternion(ori.x, ori.y, ori.z, ori.w);
          const down = new THREE.Vector3(0, -1, 0);
          let horizontalDir: THREE.Vector3;
          if (pending.deviceHeading != null) {
            const angleRad = ((pending.deviceHeading - pending.bearing) * Math.PI) / 180;
            horizontalDir = new THREE.Vector3(0, 0, -1)
              .applyQuaternion(viewerQuat)
              .applyAxisAngle(new THREE.Vector3(0, 1, 0), angleRad);
          } else {
            horizontalDir = new THREE.Vector3(0, 0, -1).applyQuaternion(viewerQuat);
          }
          horizontalDir.y = 0;
          if (horizontalDir.lengthSq() < 1e-6) {
            horizontalDir.set(0, 0, -1).applyQuaternion(viewerQuat);
            horizontalDir.y = 0;
            if (horizontalDir.lengthSq() >= 1e-6) {
              horizontalDir.normalize();
            }
          } else {
            horizontalDir.normalize();
          }
          const placePos = viewerPos
            .clone()
            .addScaledVector(horizontalDir, pending.horizontalDist)
            .addScaledVector(down, pending.deltaAlt);
          const prevGeoPlaced = geoPlacedRef.current;
          if (prevGeoPlaced) {
            ctx.scene.remove(prevGeoPlaced);
            geoPlacedRef.current = null;
          }
          const placed = arModel.clone();
          placed.position.copy(placePos);
          placed.quaternion.copy(viewerQuat);
          ctx.scene.add(placed);
          geoPlacedRef.current = placed;
          geoPlacementPendingRef.current = null;

          const loadedModel = loadedSceneRef.current;
          if (loadedModel) loadedModel.visible = false;

          const prevMarker = geoMarkerRef.current;
          if (prevMarker) {
            ctx.scene.remove(prevMarker);
            (prevMarker.geometry as THREE.BufferGeometry).dispose();
            (prevMarker.material as THREE.Material).dispose();
          }
          const marker = new THREE.Mesh(
            new THREE.BoxGeometry(1, 1, 1),
            new THREE.MeshBasicMaterial({ color: 0xff0000, wireframe: true })
          );
          marker.position.copy(placePos);
          marker.scale.setScalar(0.5);
          ctx.scene.add(marker);
          geoMarkerRef.current = marker;
        } else {
          pending.retryCount += 1;
          if (pending.retryCount >= GEO_PLACEMENT_MAX_RETRIES) {
            geoPlacementPendingRef.current = null;
            setLocationOnErrorRef.current?.(
              '모델을 배치할 수 없습니다. AR 환경과 위치 권한을 확인해 주세요.'
            );
            locationModeActiveRef.current = false;
            setLocationModeActiveRef.current?.(false);
          }
        }
      }
    };

    const ctx = createThreeScene(containerRef.current, { onXRFrame });
    contextRef.current = ctx;

    const reticle = new THREE.Mesh(
      new THREE.RingGeometry(0.15, 0.2, 32).rotateX(-Math.PI / 2),
      new THREE.MeshBasicMaterial({ color: 0xffffff })
    );
    reticle.matrixAutoUpdate = false;
    reticle.visible = false;
    ctx.scene.add(reticle);
    reticleRef.current = reticle;

    const controller = ctx.renderer.xr.getController(0);
    controller.addEventListener('select', () => {
      if (locationModeActiveRef.current) return;
      const ctx = contextRef.current;
      const reticle = reticleRef.current;
      const arModel = arPlaceableRef.current;
      if (!ctx || !reticle || !reticle.visible || !arModel) return;
      for (const old of tapPlacedRef.current) {
        ctx.scene.remove(old);
      }
      tapPlacedRef.current = [];
      const loadedModel = loadedSceneRef.current;
      if (loadedModel) {
        loadedModel.visible = false;
        ctx.scene.remove(loadedModel);
      }
      const placed = arModel.clone();
      placed.matrix.copy(reticle.matrix);
      placed.matrix.decompose(placed.position, placed.quaternion, placed.scale);
      ctx.scene.add(placed);
      tapPlacedRef.current.push(placed);
    });
    ctx.scene.add(controller);

    const container = arButtonContainerRef.current;
    const useNativeIOS = isIOS();
    let arButton: HTMLButtonElement;

    if (useNativeIOS) {
      arButton = document.createElement('button');
      arButton.id = 'ARButton';
      arButton.textContent = 'START AR';
      arButton.type = 'button';
      arButton.style.cssText = 'position:relative;left:"";bottom:"";display:none;font-family:Orbitron,sans-serif;width:100%;padding:12px 16px;border:1px solid rgba(255,255,255,0.5);border-radius:6px;background:rgba(0,0,0,0.7);color:white;cursor:pointer;font-size:14px;';
      arButton.addEventListener('click', () => {
        alert('IOS 버전 기능 구현중입니다..\nMAC 구매하면 기능구현 하겠습니다..');
      });
    } else {
      arButton = ARButton.createButton(ctx.renderer, {
        requiredFeatures: ['hit-test'],
        ...(arOverlayRef.current && {
          optionalFeatures: ['dom-overlay'],
          domOverlay: { root: arOverlayRef.current },
        }),
      }) as HTMLButtonElement;
      arButton.textContent = 'AR시작';
    }

    if (container) {
      const existing = container.querySelector('#ARButton');
      if (existing) existing.remove();
      const insertBefore = container.children[0] ?? null;
      if (insertBefore) {
        container.insertBefore(arButton, insertBefore);
      } else {
        container.appendChild(arButton);
      }
    }
    arButtonRef.current = arButton;
    arButton.style.position = 'relative';
    arButton.style.left = '';
    arButton.style.bottom = '';
    arButton.style.display = 'none';
    arButton.style.fontFamily = 'Orbitron, sans-serif';
    arButton.style.width = '100%';

    const handleResize = () => {
      if (containerRef.current) {
        ctx.resize(containerRef.current.clientWidth, containerRef.current.clientHeight);
      }
    };

    window.addEventListener('resize', handleResize);
    ctx.animate();

    return () => {
      window.removeEventListener('resize', handleResize);
      hitTestSourceRef.current = null;
      hitTestSourceRequestedRef.current = false;
      reticleRef.current = null;
      if (arButtonContainerRef.current?.contains(arButton)) {
        arButtonContainerRef.current.removeChild(arButton);
      }
      arButtonRef.current = null;
      ctx.dispose();
      contextRef.current = null;
    };
  }, []);

  useEffect(() => {
    if (arButtonRef.current) {
      arButtonRef.current.style.display = menuExpanded ? '' : 'none';
    }
  }, [menuExpanded]);


  // Apply opacity from meshItems to Three.js meshes
  useEffect(() => {
    meshItems.forEach((item) => {
      const mesh = meshByIdRef.current.get(item.id);
      if (mesh) setMeshMaterialOpacity(mesh, item.opacity);
    });
  }, [meshItems]);

  const loadGlbFromUrl = useCallback(
    (url: string) => {
      const ctx = contextRef.current;
      if (!ctx) return;

      setError(null);
      setLoading(true);
      meshByIdRef.current.clear();
      arPlaceableRef.current = null;
      arPlaceableGeoRef.current = null;
      setMeshItems([]);
      setModelSize(null);

      const loader = new GLTFLoader();
      loader.load(
        url,
        (gltf) => {
          const prev = loadedSceneRef.current;
          if (prev) {
            ctx.scene.remove(prev);
            prev.traverse((child) => {
              if (child instanceof THREE.Mesh && child.geometry) {
                child.geometry.dispose();
                if (child.material) {
                  const materials = Array.isArray(child.material) ? child.material : [child.material];
                  materials.forEach((m) => m.dispose());
                }
              }
            });
          }

          const model = gltf.scene;
          ctx.scene.add(model);
          loadedSceneRef.current = model;

          const arClone = model.clone();
          const arBox = new THREE.Box3().setFromObject(arClone);
          const arCenter = arBox.getCenter(new THREE.Vector3());
          arClone.position.sub(arCenter);
          arPlaceableRef.current = arClone;
          const arGeoClone = model.clone();
          const arGeoBox = new THREE.Box3().setFromObject(arGeoClone);
          const arGeoCenter = arGeoBox.getCenter(new THREE.Vector3());
          arGeoClone.position.sub(arGeoCenter);
          arPlaceableGeoRef.current = arGeoClone;

          const meshes: MeshItem[] = [];
          model.traverse((child) => {
            if (child instanceof THREE.Mesh) {
              const id = child.uuid;
              setMeshMaterialOpacity(child, 1);
              meshByIdRef.current.set(id, child);
              meshes.push({
                id,
                name: getObjectDisplayName(child),
                opacity: 1,
              });
            }
          });
          setMeshItems(meshes);

          const box = new THREE.Box3().setFromObject(model);
          const size = box.getSize(new THREE.Vector3());
          const center = box.getCenter(new THREE.Vector3());
          model.position.sub(center);

          setModelSize({
            width: size.x,
            height: size.y,
            depth: size.z,
          });

          model.updateMatrixWorld(true);
          frameCameraToModel(ctx, model);

          setLoading(false);
        },
        undefined,
        (err: unknown) => {
          setError(err instanceof Error ? err.message : 'Failed to load model');
          setLoading(false);
        }
      );
    },
    [setMeshItems, setModelSize]
  );

  useEffect(() => {
    if (initialModelUrl) loadGlbFromUrl(initialModelUrl);
  }, [initialModelUrl, loadGlbFromUrl]);

  const handleResetView = () => {
    const ctx = contextRef.current;
    const model = loadedSceneRef.current;
    if (ctx) {
      if (model) {
        model.position.set(0, 0, 0);
        model.quaternion.identity();
        model.scale.set(1, 1, 1);
        frameCameraToModel(ctx, model);
      } else {
        ctx.resetView();
      }
    }
  };

  const handleEndAR = () => {
    contextRef.current?.renderer?.xr?.getSession()?.end();
    setLocationModeActive(false);
    locationModeActiveRef.current = false;
    const ctx = contextRef.current;
    const loadedModel = loadedSceneRef.current;
    if (loadedModel && ctx) {
      if (!loadedModel.parent) ctx.scene.add(loadedModel);
      loadedModel.visible = true;
    }
  };

  const initialModelUrlRef = useRef(initialModelUrl);
  initialModelUrlRef.current = initialModelUrl;

  const STEP_LAT_LON = 0.000001; // 위·경도 1클릭 = 0.000001°
  const SLIDER_ALT_STEP = 0.001; // 고도 슬라이더 1틱 = 1mm
  const HOLD_ACCELERATE_MS = 500; // 0.5초 이상 꾹 누르면 빠르게 변동
  const HOLD_REPEAT_MS = 80; // 꾹 누를 때 반복 간격

  const holdRepeatRef = useRef<{
    timeoutId: ReturnType<typeof setTimeout>;
    intervalId: ReturnType<typeof setInterval> | null;
  } | null>(null);

  const applyOffsetAndReplace = useCallback(
    (offset: { lat: number; lon: number; alt: number }) => {
      const geo = modelGeoLocationRef.current;
      const best = bestPositionRef.current;
      if (!geo || !best) return;
      const targetLat = geo.lat + offset.lat;
      const targetLon = geo.lon + offset.lon;
      const targetAlt = (geo.alt ?? 0) + offset.alt;
      const horizontalDistRaw = getDistanceMeters(best.lat, best.lon, targetLat, targetLon);
      const horizontalDist = Math.min(horizontalDistRaw, 150);
      const bearing = getBearing(best.lat, best.lon, targetLat, targetLon);
      const deltaAlt = best.alt - targetAlt;

      const ctx = contextRef.current;
      if (ctx) {
        const geoObj = geoPlacedRef.current;
        if (geoObj) {
          ctx.scene.remove(geoObj);
          geoPlacedRef.current = null;
        }
        const marker = geoMarkerRef.current;
        if (marker) {
          ctx.scene.remove(marker);
          (marker.geometry as THREE.BufferGeometry).dispose();
          (marker.material as THREE.Material).dispose();
          geoMarkerRef.current = null;
        }
      }

      geoPlacementPendingRef.current = {
        horizontalDist,
        deltaAlt,
        bearing,
        deviceHeading: lastPlacementDeviceHeadingRef.current,
        retryCount: 0,
      };
    },
    []
  );

  const adjustTargetOffset = useCallback(
    (dLat: number, dLon: number, dAlt: number) => {
      setTargetOffset((prev) => {
        const next = {
          lat: prev.lat + dLat,
          lon: prev.lon + dLon,
          alt: prev.alt + dAlt,
        };
        targetOffsetRef.current = next;
        applyOffsetAndReplace(next);
        return next;
      });
    },
    [applyOffsetAndReplace]
  );

  const clearHoldRepeat = useCallback(() => {
    if (holdRepeatRef.current) {
      clearTimeout(holdRepeatRef.current.timeoutId);
      if (holdRepeatRef.current.intervalId) clearInterval(holdRepeatRef.current.intervalId);
      holdRepeatRef.current = null;
    }
  }, []);

  const handleLocationRefresh = useCallback(() => {
    const geo = modelGeoLocationRef.current;
    if (!geo) return;
    if (!navigator.geolocation) {
      setLocationOnError('이 브라우저는 위치 서비스를 지원하지 않습니다.');
      return;
    }
    setLocationRefreshLoading(true);
    setLocationOnError(null);

    const ctx = contextRef.current;
    if (ctx) {
      const geoObj = geoPlacedRef.current;
      if (geoObj) {
        ctx.scene.remove(geoObj);
        geoPlacedRef.current = null;
      }
      const marker = geoMarkerRef.current;
      if (marker) {
        ctx.scene.remove(marker);
        (marker.geometry as THREE.BufferGeometry).dispose();
        (marker.material as THREE.Material).dispose();
        geoMarkerRef.current = null;
      }
    }
    geoPlacementPendingRef.current = null;

    navigator.geolocation.getCurrentPosition(
      (pos) => {
        const lat = pos.coords.latitude;
        const lon = pos.coords.longitude;
        const alt = pos.coords.altitude ?? 0;
        const accuracy = pos.coords.accuracy ?? 999;
        bestPositionRef.current = { lat, lon, alt, accuracy };
        smoothedPositionRef.current = { lat, lon, alt };
        setUserGeoLocation({ lat, lon, alt });
        lastUserGeoUpdateRef.current = Date.now();
        applyOffsetAndReplace(targetOffsetRef.current);
        setLocationRefreshLoading(false);
      },
      (err) => {
        setLocationOnError(err.message || '위치를 가져올 수 없습니다.');
        setLocationRefreshLoading(false);
      },
      { enableHighAccuracy: true, maximumAge: 0, timeout: 15000 }
    );
  }, [applyOffsetAndReplace]);

  const handleLocationOn = useCallback(() => {
    const url = initialModelUrlRef.current;
    const code = arCodeRef.current;
    const geo = modelGeoLocationRef.current;
    if (!url) {
      setLocationOnError('모델을 먼저 불러와 주세요.');
      return;
    }
    setLocationOnError(null);
    setLocationOnInfo(null);

    if (geo) {
      locationModeActiveRef.current = true;
      setLocationModeActive(true);
      handleLocationRefresh();
      return;
    }

    // 마커 모드는 카메라 필요 → HTTPS 필수
    if (typeof window !== 'undefined' && !window.isSecureContext) {
      setLocationOnError(
        '마커 카메라를 사용하려면 HTTPS가 필요합니다. http:// 대신 https:// 로 접속하세요.'
      );
      return;
    }

    const session = contextRef.current?.renderer?.xr?.getSession();
    if (session) session.end();
    setLocationModeActive(false);
    locationModeActiveRef.current = false;
    // WebXR/WebGL 정리 후 리다이렉트 (탭 크래시 방지)
    // geo 없을 때: 모바일 → QR 스캔 화면, PC → AR.js 마커 화면
    setTimeout(() => {
      if (isMobile()) {
        router.push(code ? `/ar/marker?code=${code}&mode=qr` : '/ar/marker?mode=qr');
      } else {
        router.push(code ? `/ar/marker?code=${code}` : '/ar/marker');
      }
    }, 400);
  }, [router, handleLocationRefresh]);

  const makeOffsetButtonHandlers = useCallback(
    (dLat: number, dLon: number, dAlt: number) => ({
      onPointerDown: (e: React.PointerEvent) => {
        e.preventDefault();
        adjustTargetOffset(dLat, dLon, dAlt);
        clearHoldRepeat();
        const timeoutId = setTimeout(() => {
          const intervalId = setInterval(() => {
            adjustTargetOffset(dLat, dLon, dAlt);
          }, HOLD_REPEAT_MS);
          if (holdRepeatRef.current) {
            holdRepeatRef.current.intervalId = intervalId;
          }
        }, HOLD_ACCELERATE_MS);
        holdRepeatRef.current = {
          timeoutId,
          intervalId: null,
        };
      },
      onPointerUp: clearHoldRepeat,
      onPointerLeave: clearHoldRepeat,
      onPointerCancel: clearHoldRepeat,
      onContextMenu: (e: React.MouseEvent) => e.preventDefault(),
    }),
    [adjustTargetOffset, clearHoldRepeat]
  );

  const handleLocationOff = useCallback(() => {
    clearHoldRepeat();
    setLocationRefreshLoading(false);
    locationModeActiveRef.current = false;
    setLocationModeActive(false);
    setLocationOnError(null);
    setLocationOnInfo(null);
    setUserGeoLocation(null);
    setTargetOffset({ lat: 0, lon: 0, alt: 0 });
    targetOffsetRef.current = { lat: 0, lon: 0, alt: 0 };
    if (placementTimeoutRef.current) {
      clearTimeout(placementTimeoutRef.current);
      placementTimeoutRef.current = null;
    }
    if (geolocationWatchIdRef.current != null) {
      navigator.geolocation.clearWatch(geolocationWatchIdRef.current);
      geolocationWatchIdRef.current = null;
    }
    const ctx = contextRef.current;
    if (ctx) {
      const loadedModel = loadedSceneRef.current;
      if (loadedModel) loadedModel.visible = true;
      const geoObj = geoPlacedRef.current;
      if (geoObj) {
        ctx.scene.remove(geoObj);
        geoPlacedRef.current = null;
      }
      const marker = geoMarkerRef.current;
      if (marker) {
        ctx.scene.remove(marker);
        (marker.geometry as THREE.BufferGeometry).dispose();
        (marker.material as THREE.Material).dispose();
        geoMarkerRef.current = null;
      }
      const arrowEl = arrowIndicatorRef.current;
      if (arrowEl) arrowEl.style.display = 'none';
    }
  }, [clearHoldRepeat]);

  return (
    <div
      className={`absolute inset-0 w-full h-full ${className}`}
      aria-label="AR Viewer"
    >
      {/* WebXR dom-overlay: AR 모드에서만 보이며, 투명도 패널과 닫기 버튼 표시 */}
      <div
        ref={arOverlayRef}
        style={{ display: 'none' }}
        className="pointer-events-none fixed inset-0 z-[1000]"
        aria-hidden
      >
        <div className="pointer-events-auto absolute left-5 top-5 z-10 flex flex-col gap-1">
          <button
            type="button"
            onClick={handleLocationOn}
            disabled={!initialModelUrl}
            className="rounded border border-white/80 bg-black/50 px-4 py-2 text-sm text-white opacity-90 outline-none transition-opacity hover:opacity-100 disabled:opacity-50 disabled:cursor-not-allowed"
            aria-label="Location ON"
            title={initialModelUrl ? '마커를 비춰 모델을 배치합니다' : '모델을 먼저 불러와 주세요'}
          >
            Location ON
          </button>
          {locationOnError && (
            <p className="max-w-[200px] rounded bg-red-900/90 px-2 py-1 text-xs text-white">
              {locationOnError}
            </p>
          )}
          {locationOnInfo && !locationOnError && (
            <p className="max-w-[200px] rounded bg-blue-900/70 px-2 py-1 text-xs text-white">
              {locationOnInfo}
            </p>
          )}
        </div>
        {locationModeActive && (
          <div
            ref={arrowIndicatorRef}
            className="pointer-events-none absolute z-20 flex -translate-x-1/2 -translate-y-1/2 flex-col items-center gap-0.5"
            style={{
              display: 'none',
              filter: 'drop-shadow(0 0 4px rgba(0,0,0,0.5))',
              animation: 'arrow-pulse 1.5s ease-in-out infinite',
            }}
            aria-hidden
          >
            <span
              ref={arrowDistanceRef}
              className="text-sm font-bold text-white/95 tabular-nums"
              style={{ textShadow: '0 1px 2px rgba(0,0,0,0.8)' }}
            />
            <svg
              width="48"
              height="48"
              viewBox="0 0 24 24"
              fill="none"
              xmlns="http://www.w3.org/2000/svg"
            >
              <path
                d="M4 20 L12 4 L20 20"
                stroke="white"
                strokeWidth="2.5"
                strokeLinecap="round"
                strokeLinejoin="round"
                fill="none"
                strokeOpacity="0.85"
              />
            </svg>
          </div>
        )}
        {locationModeActive && (
          <div className="pointer-events-auto absolute right-5 top-20 z-10 flex flex-col rounded-lg border border-white/40 bg-black/50 overflow-hidden">
            <button
              type="button"
              onClick={() => setLocationOffsetPanelExpanded((e) => !e)}
              className="flex w-full items-center justify-between px-3 py-2 text-left text-[10px] text-white/80 transition-opacity hover:text-white/95 hover:opacity-90"
              aria-expanded={locationOffsetPanelExpanded}
              aria-label={locationOffsetPanelExpanded ? '위치 미세조절 패널 접기' : '위치 미세조절 패널 펼치기'}
            >
              <span>위치 미세조절</span>
              <span className="transition-transform" style={{ transform: locationOffsetPanelExpanded ? 'rotate(180deg)' : 'rotate(0)' }}>
                ▼
              </span>
            </button>
            {locationOffsetPanelExpanded && (
            <div className="flex flex-col gap-3 border-t border-white/20 p-2">
            <div className="grid grid-cols-3 gap-0.5">
              <div />
              <button
                type="button"
                {...makeOffsetButtonHandlers(STEP_LAT_LON, 0, 0)}
                className="flex h-8 w-8 items-center justify-center rounded bg-white/20 text-white hover:bg-white/30"
                aria-label="위도 증가"
              >
                <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                  <path d="M18 15l-6-6-6 6" />
                </svg>
              </button>
              <div />
              <button
                type="button"
                {...makeOffsetButtonHandlers(0, -STEP_LAT_LON, 0)}
                className="flex h-8 w-8 items-center justify-center rounded bg-white/20 text-white hover:bg-white/30"
                aria-label="경도 감소"
              >
                <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                  <path d="M15 18l-6-6 6-6" />
                </svg>
              </button>
              <div className="flex h-8 w-8 items-center justify-center rounded bg-white/10 text-[8px] text-white/70">
                •
              </div>
              <button
                type="button"
                {...makeOffsetButtonHandlers(0, STEP_LAT_LON, 0)}
                className="flex h-8 w-8 items-center justify-center rounded bg-white/20 text-white hover:bg-white/30"
                aria-label="경도 증가"
              >
                <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                  <path d="M9 18l6-6-6-6" />
                </svg>
              </button>
              <div />
              <button
                type="button"
                {...makeOffsetButtonHandlers(-STEP_LAT_LON, 0, 0)}
                className="flex h-8 w-8 items-center justify-center rounded bg-white/20 text-white hover:bg-white/30"
                aria-label="위도 감소"
              >
                <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                  <path d="M6 9l6 6 6-6" />
                </svg>
              </button>
              <div />
            </div>
            <div className="flex items-center gap-1">
              <span className="w-8 text-[9px] text-white/70">고도</span>
              <input
                type="range"
                min={-500}
                max={500}
                value={Math.round(targetOffset.alt / SLIDER_ALT_STEP)}
                onChange={(e) => {
                  const newAlt = Number(e.target.value) * SLIDER_ALT_STEP;
                  setTargetOffset((prev) => {
                    const next = { ...prev, alt: newAlt };
                    targetOffsetRef.current = next;
                    applyOffsetAndReplace(next);
                    return next;
                  });
                }}
                className="h-2 w-20 flex-1 accent-white/80"
              />
              <span className="w-10 text-[9px] text-white/70 tabular-nums">
                {(targetOffset.alt * 1000).toFixed(2)}mm
              </span>
            </div>
            <button
              type="button"
              onClick={handleLocationRefresh}
              disabled={locationRefreshLoading}
              className="flex items-center justify-center gap-1.5 rounded bg-white/20 px-2 py-1.5 text-[10px] text-white transition-opacity hover:bg-white/30 disabled:opacity-50"
              aria-label="위치 새로 고침"
              title="현재 위치를 다시 측정하여 모델을 재배치합니다"
            >
              {locationRefreshLoading ? (
                <>
                  <span className="h-2.5 w-2.5 animate-spin rounded-full border border-white/50 border-t-white" aria-hidden />
                  <span>측정 중…</span>
                </>
              ) : (
                <>
                  <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden>
                    <path d="M23 4v6h-6" />
                    <path d="M20.49 15a9 9 0 1 1-2.12-9.36L23 10" />
                  </svg>
                  <span>위치 새로 고침</span>
                </>
              )}
            </button>
            </div>
            )}
          </div>
        )}
        <div className="pointer-events-auto absolute right-5 top-5 z-10">
          <button
            type="button"
            onClick={handleEndAR}
            className="flex h-10 w-10 items-center justify-center rounded-full border border-white/80 bg-black/50 text-white opacity-90 outline-none transition-opacity hover:opacity-100"
            aria-label="AR 종료"
          >
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
              <path d="M6 6l12 12M18 6L6 18" />
            </svg>
          </button>
        </div>
        {locationModeActive && (userGeoLocation || modelGeoLocation) && (
          <div className="pointer-events-none absolute bottom-16 left-0 right-0 px-4 pb-2">
            <div className="rounded bg-black/60 px-3 py-2 text-xs text-white/90">
              {userGeoLocation && (
                <p className="mb-1">
                  <span className="text-white/70">내 위치:</span>{' '}
                  {userGeoLocation.lat.toFixed(6)}, {userGeoLocation.lon.toFixed(6)} (고도 {userGeoLocation.alt.toFixed(1)}m)
                </p>
              )}
              {modelGeoLocation && (
                <p>
                  <span className="text-white/70">목표 위치:</span>{' '}
                  {(modelGeoLocation.lat + targetOffset.lat).toFixed(6)}, {(modelGeoLocation.lon + targetOffset.lon).toFixed(6)} (고도 {((modelGeoLocation.alt ?? 0) + targetOffset.alt).toFixed(3)}m)
                </p>
              )}
            </div>
          </div>
        )}
        <div className="pointer-events-auto absolute bottom-0 left-0 right-0">
          <ControlPanel meshItems={meshItems} setMeshItems={setMeshItems} />
        </div>
      </div>
      <div ref={containerRef} className="absolute inset-0 w-full h-full" />
      <div className="absolute right-4 top-4 z-10 flex flex-col items-end gap-2">
        <button
          type="button"
          onClick={() => setMenuExpanded((e) => !e)}
          className="flex items-center justify-center rounded border border-white bg-black/10 p-2 text-white opacity-50 outline-none transition-opacity hover:opacity-100"
          aria-expanded={menuExpanded}
          aria-label={menuExpanded ? '메뉴 접기' : '메뉴 펼치기'}
        >
          <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden>
            <path d="M12 15a3 3 0 1 0 0-6 3 3 0 0 0 0 6Z" />
            <path d="M19.4 15a1.65 1.65 0 0 0 .33 1.82l.06.06a2 2 0 0 1 0 2.83 2 2 0 0 1-2.83 0l-.06-.06a1.65 1.65 0 0 0-1.82-.33 1.65 1.65 0 0 0-1 1.51V21a2 2 0 0 1-2 2 2 2 0 0 1-2-2v-.09A1.65 1.65 0 0 0 9 19.4a1.65 1.65 0 0 0-1.82.33l-.06.06a2 2 0 0 1-2.83 0 2 2 0 0 1 0-2.83l.06-.06a1.65 1.65 0 0 0 .33-1.82 1.65 1.65 0 0 0-1.51-1H3a2 2 0 0 1-2-2 2 2 0 0 1 2-2h.09A1.65 1.65 0 0 0 4.6 9a1.65 1.65 0 0 0-.33-1.82l-.06-.06a2 2 0 0 1 0-2.83 2 2 0 0 1 2.83 0l.06.06a1.65 1.65 0 0 0 1.82.33H9a1.65 1.65 0 0 0 1-1.51V3a2 2 0 0 1 2-2 2 2 0 0 1 2 2v.09a1.65 1.65 0 0 0 1 1.51 1.65 1.65 0 0 0 1.82-.33l.06-.06a2 2 0 0 1 2.83 0 2 2 0 0 1 0 2.83l-.06.06a1.65 1.65 0 0 0-.33 1.82V9a1.65 1.65 0 0 0 1.51 1H21a2 2 0 0 1 2 2 2 2 0 0 1-2 2h-.09a1.65 1.65 0 0 0-1.51 1z" />
          </svg>
        </button>
        <div
          ref={arButtonContainerRef}
          className={`flex w-max flex-col gap-2 rounded border border-white/50 bg-black/70 p-3 ${menuExpanded ? '' : 'hidden'}`}
        >
          <button
            type="button"
            onClick={handleResetView}
            className="rounded border border-white bg-black/10 px-5 py-2 text-center text-[13px] text-white opacity-50 outline-none transition-opacity hover:opacity-100"
          >
            RESET
          </button>
          <button
            type="button"
            onClick={() => setGuideModalOpen(true)}
            className="rounded border border-white bg-black/10 px-5 py-2 text-center text-[13px] text-white opacity-50 outline-none transition-opacity hover:opacity-100"
          >
            설명서
          </button>
        </div>
      </div>
      {meshItems.length === 0 && (
        <div className="absolute left-1/2 top-1/2 z-10 flex -translate-x-1/2 -translate-y-1/2 flex-col items-center gap-4">
          <Image
            src="/ar-placeholder.png"
            alt="3D 건물 미리보기"
            width={280}
            height={200}
            className="w-full max-w-[280px] object-contain"
          />
        </div>
      )}
      {error && (
        <p className="absolute left-1/2 top-[calc(50%+5rem)] z-10 max-w-xs -translate-x-1/2 rounded bg-red-900/90 px-3 py-2 text-center text-sm text-white">
          {error}
        </p>
      )}
      {guideModalOpen && (
        <div
          className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 p-4"
          onClick={() => setGuideModalOpen(false)}
          role="button"
          tabIndex={0}
          onKeyDown={(e) => e.key === 'Escape' && setGuideModalOpen(false)}
        >
          <div
            className="w-full max-w-sm"
            onClick={(e) => e.stopPropagation()}
          >
            <GuideContent variant="ar" />
            <button
              type="button"
              onClick={() => setGuideModalOpen(false)}
              className="mt-3 w-full rounded border border-white/30 bg-white/10 py-2 text-sm text-white hover:bg-white/20"
            >
              닫기
            </button>
          </div>
        </div>
      )}
    </div>
  );
}
